### ISSUE TITLE
fetch_user/2, inject locale param

### ISSUE THREAD

**Issue by hykw** [ueberauth/ueberauth_facebook#10]
Facebook has your name not only written in English(alphabet), but in language-specific name such as Umlaut, Japanese kanji, etc(I attache the snapshots, just in case).

You can get the language-specific name with `https://graph.facebook.com/me?locale=ja_JP&access_token=xxxxxx`. Is it possible to specify locale when you fetch user data?(maybe injecting it in fetch_user/2, path parameter)

![facebook1](https://cloud.githubusercontent.com/assets/1897735/12712952/3f33ec90-c90f-11e5-8c12-2757e5083352.png)

![facebook2](https://cloud.githubusercontent.com/assets/1897735/12712956/433392fa-c90f-11e5-933f-cccf95c313c2.png)

**Comment by doomspork** [comment]
Hey @hykw, can you check out the latest version?  I just released a new version with the changes @hassox made in #11

**Comment by hykw** [comment]
No, it doesn't work.

It seems locale is added to authorize_url, but it should be specified when you fetch user info(in fetch_user/2, line 134: `path = "/me?fields=#{option(conn, :profile_fields)}&locale=ja_JP"`), because authorization process doesn't need any locale information, but fetching user info does.

My configuration is following, btw.

``` elixir
config :ueberauth, Ueberauth,
  providers: [
    facebook: {Ueberauth.Strategy.Facebook, [
        profile_fields: "name,email",
        request_path: "/social_login/facebook",
        callback_path: "/social_login/facebook_callback/",
        auth_type: "rerequest",
        locale: "ja_JP",
    ]}
  ]
```

**Comment by hassox** [comment]
I think you will need to define a list of 
    allowed_request_params

If you look in lib/strategies/facebook.ex you can see the defaults

**Comment by doomspork** [comment]
@hassox I think what @hykw is suggesting is that we need to update [`fetch_user/2`](https://github.com/ueberauth/ueberauth_facebook/blob/master/lib/ueberauth/strategy/facebook.ex#L134):

``` elixir
defp fetch_user(conn, token) do
  conn = put_private(conn, :facebook_token, token)
  path = "/me?fields=#{option(conn, :profile_fields)}"
  case OAuth2.AccessToken.get(token, path) do
   # do stuff
  end
end
```

To something like:

``` elixir
defp fetch_user(conn, token) do
  conn = put_private(conn, :facebook_token, token)
  path = "/me?fields=#{option(conn, :profile_fields)}&locale=#{option(conn, :locale)}"
  case OAuth2.AccessToken.get(token, path) do
   # do stuff
  end
end
```

@hykw do you know the default locale is?

**Comment by hykw** [comment]
@doomspork Yes, that's what I thought. locale option have to be set to `https://graph.facebook.com/me`

> @hykw do you know the default locale is?

The default locale is empty(`/me?fields=#{option(conn, :profile_fields)}`), because you, includes Facebook, cannot determine the default(because it's not lang but locale, such as, en_CA, en_us. en_GB, etc...).

**Comment by doomspork** [comment]
@hykw I opened a PR with a new change I _think_ should solve this for you.  Can you take a peek at #13 when you have a chance?

Thanks!
