### ISSUE TITLE
Release with latest changes from master

### ISSUE THREAD

**Issue by ajibarra** [ueberauth/ueberauth_facebook#26]
Please create a new release with the latest commit from master which locks the oauth2 lib to 0.6.0 because ueberauth_facebook 0.4.0 required oauth2 >0.5 which installs 0.7.0 and breaks everything.

Thanks

**Comment by charleshan** [comment]
+1. Temporary solution for the time being:

```
# mix.exs

defp deps do
  [
    {:ueberauth_facebook, git: "https://github.com/ueberauth/ueberauth_facebook.git", ref: "2e3c118"}
  ]
end
```

**Comment by charleshan** [comment]
@doomspork could you push the package to hex?

**Comment by doomspork** [comment]
A new version was released last week along with the other packages.

**Comment by MillionIntegrals** [comment]
It seems it's not available in hex, this website: https://hex.pm/packages/ueberauth_facebook still shows version 0.4.0 as the latest one.

**Comment by doomspork** [comment]
Alrighty, I published it again.  Take a peek @MillionIntegrals 👍

**Comment by MillionIntegrals** [comment]
Yes, it's there now. Thank you for that, this probably can be closed now.
