### ISSUE TITLE
Mismatch of dependencies between mix.exs and hex.pm

### ISSUE THREAD

**Issue by mdlkxzmcp** [ueberauth/ueberauth_facebook#50]
The [hex.pm](https://hex.pm/packages/ueberauth_facebook) dependencies are
```
oauth2 ~> 0.9
ueberauth ~> 0.4
```
while the [mix.exs](https://github.com/ueberauth/ueberauth_facebook/blob/master/mix.exs) file (which got changed more recently) are
```
{:ueberauth, "~> 0.6.0"},
{:oauth2, "~> 1.0 or ~> 2.0"}
```

**Comment by alexandrubagu** [comment]
I had the same problem. The quick fix was to use github repo and fix it to a commit ref like this:

```elixir
{:ueberauth_google, "~> 0.9"},
{:ueberauth_facebook, github: "ueberauth/ueberauth_facebook", ref: "a351a25fa6f175116f8dd3b075bbe622604db5be"}
```

**Comment by alexandrubagu** [comment]
Can you release a new version for `ueberauth_facebook` ? @doomspork @hassox @scrogson 

Thanks,

**Comment by Hanspagh** [comment]
This is fixed now

**Comment by alexandrubagu** [comment]
Thanks, @Hanspagh
