### ISSUE TITLE
Is there a 0.2 version?

### ISSUE THREAD

**Issue by micahwedemeyer** [ueberauth/ueberauth_facebook#6]
(Elixir / Phoenix newb, sorry for that)

I was working on getting it installed, and I got hung up on the deps section. I eventually got v 0.1.4 installed, but the README says 0.2 Is that just a copy/paste error from the ueberauth main repo?

**Comment by hassox** [comment]
Hey @micahwedemeyer it's in the release pipeline. @doomspork is releasing it today/tomorrow

**Comment by micahwedemeyer** [comment]
Thanks! Loving Elixir/Phoenix/Uber so far...

**Comment by doomspork** [comment]
Sorry @micahwedemeyer, 0.2.0 has been pushed.  I'm pushing 0.2.1 with some Graph API changes shortly.

**Comment by doomspork** [comment]
0.2.1 with Graph API fixes is out now too.  Thanks @micahwedemeyer :+1:
