### ISSUE TITLE
OTP 24 :crypto fix not in any release/not on Hex.pm

### ISSUE THREAD

**Issue by njwest** [ueberauth/ueberauth_facebook#62]
The `crypto.hmac/3 -> crypto.mac/4` fix for OTP 24 is on master in this repo, but this fix has not been released to [Hex.pm](https://hex.pm/packages/ueberauth_facebook), which still serves Ueberauth FB 8.1.

Any timeline for hex publication, or ya'll need a hand with any related chores?

Thanks for the great FB Ueberauth package!

**Comment by shleeable** [comment]
Hey, this has caused an outage on my app. Anybody able to ping the devs directly?

**Comment by yordis** [comment]
Done!

**Comment by shleeable** [comment]
Thanks
