### ISSUE TITLE
Currently published ueberauth_facebook incompatible with latest Ueberauth

### ISSUE THREAD

**Issue by njwest** [ueberauth/ueberauth_facebook#66]
#65  was merged but not released to Hex.pm, so I'm currently manually getting the master branch like so in `mix.exs`:

```elixir
      {:ueberauth_facebook, git: "https://github.com/ueberauth/ueberauth_facebook.git", branch: "master"},
```

Any timeline for publication to Hex.pm, or is there anything I can do to help speed up the process?

Thank you for the great free software!

**Comment by yordis** [comment]
Done
